# This file deliberately contains only the values that differ from the 
# Default values for Camunda Platform helm.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  image:
    tag: latest
zeebe:
  enabled: false
zeebe-gateway:
  enabled: false
operate:
  enabled: false
tasklist:
  enabled: false
optimize:
  enabled: true
  image:
    tag: latest
  partitionCount: "1"
identity:
  enabled: true
elasticsearch:
  enabled: false
